[tool.poetry]
name = "203_project"
version = "0.1.0"
description = "203 project"
authors = ["Maelys 2"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
